apiVersion: v1
kind: Service
metadata:
  name: jenkins-internal
  labels:
    app: jenkins
spec:
  ports:
    - name: gui
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: jnlp
      protocol: TCP
      port: 50000
      targetPort: 50000
  selector:
    app: jenkins